using System.Text.RegularExpressions;

namespace PgNimbus.Core.Text;

public static partial class SqlCompletionContext
{
    /// <summary>
    /// True when the word at the caret is where a <i>new</i> name is written —
    /// an alias after a FROM/JOIN/UPDATE item or after <c>AS</c>, a CTE's name,
    /// the object named by <c>CREATE …</c>, a column in a table definition, the
    /// new name of an <c>ALTER … RENAME … TO</c>. Nothing in the catalog is
    /// what the user means there, even when a row happens to share the letters
    /// (<c>FROM customers c</c> is not <c>CROSS</c>, <c>AS manager</c> is not
    /// <c>manager_id</c>), so the popup may show rows but Enter takes one only
    /// when it was chosen (docs/design/sql-completion-audit-2.md §6.1).
    /// </summary>
    public static bool IsNewNamePosition(string sql, int caret)
    {
        caret = Math.Clamp(caret, 0, sql.Length);
        var wordStart = WordStart(sql, caret);
        var context = GetCaretContext(sql, caret);
        if (context.InStringOrComment)
        {
            return false;
        }

        if (context.InQuotedIdentifier)
        {
            wordStart = SqlLexer.Tokenize(sql, 0, caret)[^1].Start;
        }

        // A qualified name being typed ("CREATE TABLE app.|") is judged by
        // where its first part starts.
        var nameStart = wordStart;
        while (nameStart > 0 && sql[nameStart - 1] == '.' && ReadNameBackward(sql, nameStart - 1) is { } part)
        {
            nameStart = part.Start;
        }

        var (statementStart, _) = CompletionStatementSpan(sql, caret);
        var tokens = Significant(sql, statementStart, nameStart);
        if (tokens.Count == 0)
        {
            return false;
        }

        var last = tokens[^1];
        if (nameStart == wordStart && IsWord(sql, last, "as"))
        {
            return IsAliasAs(sql, tokens, caret);
        }

        return IsCteName(sql, tokens)
            || IsCreatedName(sql, tokens)
            || IsColumnDefinitionName(sql, tokens)
            || IsAlterNewName(sql, tokens)
            || (nameStart == wordStart && IsAliasAfterItem(sql, tokens, statementStart, wordStart));
    }

    // The statement's tokens before `end`, trivia dropped.
    private static List<SqlToken> Significant(string sql, int start, int end)
    {
        var tokens = new List<SqlToken>();
        foreach (var token in SqlLexer.Tokenize(sql, start, end))
        {
            if (!token.IsTrivia)
            {
                tokens.Add(token);
            }
        }

        return tokens;
    }

    private static bool IsWord(string sql, SqlToken token, string word) =>
        token.Kind == SqlTokenKind.Word && sql.AsSpan(token.Start, token.Length).Equals(word, StringComparison.OrdinalIgnoreCase);

    private static string? WordOf(string sql, SqlToken token) =>
        token.Kind == SqlTokenKind.Word ? SqlLexer.FoldCase(sql.AsSpan(token.Start, token.Length)) : null;

    // The paren depth of every token (the depth it sits at, an opener at its
    // own outer level) and the index of the opener each level was entered by.
    private static int[] Depths(List<SqlToken> tokens)
    {
        var depths = new int[tokens.Count];
        var depth = 0;
        for (var i = 0; i < tokens.Count; i++)
        {
            if (tokens[i].Kind == SqlTokenKind.CloseParen && depth > 0)
            {
                depth--;
            }

            depths[i] = depth;
            if (tokens[i].Kind == SqlTokenKind.OpenParen)
            {
                depth++;
            }
        }

        return depths;
    }

    // The depth right after the last token (where the caret's word sits).
    private static int CaretDepth(List<SqlToken> tokens)
    {
        var depth = 0;
        foreach (var token in tokens)
        {
            if (token.Kind == SqlTokenKind.OpenParen)
            {
                depth++;
            }
            else if (token.Kind == SqlTokenKind.CloseParen && depth > 0)
            {
                depth--;
            }
        }

        return depth;
    }

    // "… AS |": a column or table alias, except where AS opens something else
    // — a cast's type (CAST(x AS |)), a CTE's body (WITH x AS |), and the body
    // of a CREATE … AS (a view's query, a function's definition).
    private static bool IsAliasAs(string sql, List<SqlToken> tokens, int caret)
    {
        if (SqlCallSite.At(sql, caret) is { Name: [var name] } && name == "cast")
        {
            return false;
        }

        if (CteStateBefore(sql, tokens, tokens.Count - 1) == CteState.AfterName)
        {
            return false;
        }

        // GENERATED ALWAYS AS (…) / AS IDENTITY, GENERATED BY DEFAULT AS IDENTITY.
        if (tokens.Count >= 2 && WordOf(sql, tokens[^2]) is "always" or "default")
        {
            return false;
        }

        if (!IsWord(sql, tokens[0], "create"))
        {
            return true;
        }

        // CREATE VIEW v AS …, CREATE TABLE t AS …, CREATE FUNCTION … AS $$…$$:
        // the statement's first top-level AS opens its body. Any later one
        // (inside that body's select list) is an alias again.
        var depths = Depths(tokens);
        for (var i = 1; i < tokens.Count; i++)
        {
            if (depths[i] == 0 && IsWord(sql, tokens[i], "as"))
            {
                return i != tokens.Count - 1;
            }
        }

        return true;
    }

    private enum CteState
    {
        None,
        ExpectName,
        AfterName,
        AfterAs,
        AfterBody,
    }

    // The state of a WITH list at the depth of token `upto` (exclusive), read
    // from the statement's tokens: where a CTE name is due, where its AS was
    // just written, where its body has just closed.
    private static CteState CteStateBefore(string sql, List<SqlToken> tokens, int upto)
    {
        // One state per open paren level, so a WITH inside a subquery is read
        // at its own level and a CTE body's inner tokens don't disturb it.
        var states = new Stack<(CteState State, bool IsBody)>();
        var state = CteState.None;
        for (var i = 0; i < upto; i++)
        {
            var token = tokens[i];
            switch (token.Kind)
            {
                case SqlTokenKind.OpenParen:
                    states.Push((state, state is CteState.AfterAs));
                    state = CteState.None;
                    continue;
                case SqlTokenKind.CloseParen:
                    if (states.Count > 0)
                    {
                        var (outer, isBody) = states.Pop();
                        state = isBody ? CteState.AfterBody : outer;
                    }

                    continue;
                case SqlTokenKind.Comma:
                    state = state == CteState.AfterBody ? CteState.ExpectName : CteState.None;
                    continue;
            }

            var word = WordOf(sql, token);
            state = state switch
            {
                _ when word == "with" && StartsQuery(sql, tokens, i) => CteState.ExpectName,
                CteState.ExpectName when word == "recursive" => CteState.ExpectName,
                CteState.ExpectName when token.Kind is SqlTokenKind.Word or SqlTokenKind.QuotedIdentifier => CteState.AfterName,
                CteState.AfterName when word == "as" => CteState.AfterAs,
                CteState.AfterAs when word is "not" or "materialized" => CteState.AfterAs,
                _ => CteState.None,
            };
        }

        return state;
    }

    // A WITH that opens a query (and so a CTE list): the statement's first
    // word, or one right after "(" or AS / EXPLAIN. Not "timestamp WITH time
    // zone", "WITH ORDINALITY" or "WITH CHECK OPTION".
    private static bool StartsQuery(string sql, List<SqlToken> tokens, int index) =>
        index == 0
        || tokens[index - 1].Kind == SqlTokenKind.OpenParen
        || WordOf(sql, tokens[index - 1]) is "as" or "explain" or "analyze" or "verbose";

    /// <summary>True when <paramref name="tokens"/> (significant, of one statement) end with a CTE body's closing paren.</summary>
    internal static bool IsAfterCteBody(string sql, List<SqlToken> tokens) =>
        CteStateBefore(sql, tokens, tokens.Count) == CteState.AfterBody;

    // "WITH |", "WITH RECURSIVE |", "WITH a AS (…), |".
    private static bool IsCteName(string sql, List<SqlToken> tokens) =>
        CteStateBefore(sql, tokens, tokens.Count) == CteState.ExpectName;

    // The kinds of object a CREATE names — the ones whose name is new. (An
    // extension, a cast or a transform is named by something that exists.)
    private static readonly HashSet<string> CreatedKinds = new(StringComparer.Ordinal)
    {
        "table", "view", "index", "sequence", "schema", "function", "procedure", "type", "domain",
        "trigger", "role", "user", "group", "database", "tablespace", "policy", "rule", "aggregate",
        "collation", "publication", "subscription", "server", "statistics", "conversion", "operator",
    };

    // Words that may stand between CREATE and the object kind, or between the
    // kind and its name.
    private static readonly HashSet<string> CreateModifiers = new(StringComparer.Ordinal)
    {
        "or", "replace", "temp", "temporary", "unlogged", "global", "local", "unique", "materialized",
        "recursive", "foreign", "concurrently", "constraint", "event", "trusted", "procedural", "if", "not", "exists",
    };

    // "CREATE [OR REPLACE] [TEMP …] TABLE|VIEW|INDEX … [IF NOT EXISTS] |".
    private static bool IsCreatedName(string sql, List<SqlToken> tokens)
    {
        if (!IsWord(sql, tokens[0], "create"))
        {
            return false;
        }

        var sawKind = false;
        for (var i = 1; i < tokens.Count; i++)
        {
            var word = WordOf(sql, tokens[i]);
            if (word is null)
            {
                return false;
            }

            if (CreatedKinds.Contains(word))
            {
                sawKind = true;
                continue;
            }

            if (!CreateModifiers.Contains(word))
            {
                return false;
            }
        }

        return sawKind;
    }

    // "CREATE TABLE t (|" and "CREATE TABLE t (id int, |": the next column's name.
    private static bool IsColumnDefinitionName(string sql, List<SqlToken> tokens)
    {
        if (!IsWord(sql, tokens[0], "create"))
        {
            return false;
        }

        // The table's own "(": the first opener at depth 0, right after
        // CREATE [modifiers] TABLE [IF NOT EXISTS] name[.name].
        var open = -1;
        var sawTable = false;
        for (var i = 1; i < tokens.Count; i++)
        {
            var word = WordOf(sql, tokens[i]);
            if (tokens[i].Kind == SqlTokenKind.OpenParen)
            {
                open = sawTable ? i : -1;
                break;
            }

            if (word == "table")
            {
                sawTable = true;
            }
            else if (word is "as" or "of" or "partition")
            {
                return false;
            }
        }

        if (open < 0 || CaretDepth(tokens) != 1)
        {
            return false;
        }

        var depths = Depths(tokens);
        var last = tokens.Count - 1;
        return last == open || (tokens[last].Kind == SqlTokenKind.Comma && depths[last] == 1);
    }

    // ALTER …: "ADD [COLUMN] [IF NOT EXISTS] |" (a new column) and
    // "RENAME … TO |" (a new name for the table, column or constraint).
    private static bool IsAlterNewName(string sql, List<SqlToken> tokens)
    {
        if (!IsWord(sql, tokens[0], "alter") || CaretDepth(tokens) != 0)
        {
            return false;
        }

        var i = tokens.Count - 1;
        while (i > 0 && WordOf(sql, tokens[i]) is "if" or "not" or "exists")
        {
            i--;
        }

        var word = WordOf(sql, tokens[i]);
        if (word == "column" && i > 0 && IsWord(sql, tokens[i - 1], "add"))
        {
            return true;
        }

        if (word == "to")
        {
            for (var j = i - 1; j > 0; j--)
            {
                if (IsWord(sql, tokens[j], "rename"))
                {
                    return true;
                }

                if (tokens[j].Kind is SqlTokenKind.Comma)
                {
                    break;
                }
            }
        }

        return false;
    }

    // The word right after a finished FROM/JOIN/UPDATE/MERGE item that has no
    // alias yet: "FROM customers c|", "JOIN public.orders o|", "UPDATE t x|",
    // "FROM (SELECT …) q|", "FROM generate_series(1, 3) g|".
    private static bool IsAliasAfterItem(string sql, List<SqlToken> tokens, int statementStart, int wordStart)
    {
        var last = tokens[^1];
        if (last.Kind == SqlTokenKind.CloseParen)
        {
            return IsFromItemClosedBy(sql, tokens);
        }

        if (last.Kind is not (SqlTokenKind.Word or SqlTokenKind.QuotedIdentifier) || wordStart == last.End)
        {
            return false; // the word would be glued to the name before it
        }

        var before = MaskCommentsAndStrings(sql[statementStart..wordStart]);
        var froms = FromKeywordRegex().Matches(before);
        if (froms.Count > 0)
        {
            var segment = JoinSplitRegex().Split(before[(froms[^1].Index + froms[^1].Length)..])[^1];
            if (IsBareItem(JoinTargetCompleteRegex().Match(segment)))
            {
                return true;
            }
        }

        return IsBareItem(AliasableTargetRegex().Match(before));
    }

    // A relation name with nothing after it: not a keyword read as the name,
    // and no alias yet.
    private static bool IsBareItem(Match match)
    {
        if (!match.Success || match.Groups["alias"].Success)
        {
            return false;
        }

        var (schema, table) = SplitQualified(match.Groups["table"].Value);
        return table.Length > 0 && (schema.Length > 0 || !ReservedAfterTable.Contains(table));
    }

    // True when the ")" ending `tokens` closes a subquery or a function call
    // written as a FROM/JOIN item — the one place a bare word after ")" is an alias.
    private static bool IsFromItemClosedBy(string sql, List<SqlToken> tokens)
    {
        var depth = 0;
        var open = -1;
        for (var i = tokens.Count - 1; i >= 0; i--)
        {
            if (tokens[i].Kind == SqlTokenKind.CloseParen)
            {
                depth++;
            }
            else if (tokens[i].Kind == SqlTokenKind.OpenParen && --depth == 0)
            {
                open = i;
                break;
            }
        }

        if (open <= 0)
        {
            return false;
        }

        var clause = GetCaretContext(sql, tokens[open].Start).Clause;
        if (clause is not (SqlClause.FromTableRef or SqlClause.JoinTableRef))
        {
            return false;
        }

        var previous = tokens[open - 1];
        return previous.Kind is SqlTokenKind.Comma or SqlTokenKind.QuotedIdentifier
            || (previous.Kind == SqlTokenKind.Word && WordOf(sql, previous) is not ("in" or "on" or "using" or "exists" or "values" or "any" or "all"));
    }

    // UPDATE / MERGE INTO targets and a MERGE's USING source: "UPDATE t |".
    [GeneratedRegex(
        """(?:\bupdate\s+(?:only\s+)?|\bmerge\s+into\s+|^\s*merge\b[\s\S]*\busing\s+)(?<table>(?:"[^"]+"|[\w$]+)(?:\s*\.\s*(?:"[^"]+"|[\w$]+))?)(?:\s+(?:as\s+)?(?<alias>"[^"]+"|[\w$]+))?\s+$""",
        RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    private static partial Regex AliasableTargetRegex();
}
