# Renders every design master from the one committed SVG mark.
#
#   INPUT  design/logo.svg   (generated by af-to-svg.py; there is no dark twin,
#                             the plated mark reads on light and dark alike)
#
#   OUTPUT design/masters/icon/icon-{16,24,32,48,256,1024}.png   the app tile
#          design/masters/window/window-{light,dark}-256.png     transparent glyph
#          design/masters/logo/logo.png                          README header, 1024
#          design/masters/logo/wordmark-{light,dark}.svg         lockup, text baked to paths
#          design/masters/logo/wordmark-{light,dark}.png         same at 2x
#          design/masters/logo/social-preview.png                1280x640, solid bg
#
# Every size comes off the one vector master, including 16 and 24. That is a
# change from the era when design/masters/** were hand-drawn per size: the mark
# then was a traced raster, so a downscale of it turned to mud below 32px and
# the small tiles had to be redrawn by hand. The modular vector master
# rasterises cleanly, and one source beats six that drift apart. If a size ever
# does stop reading, the fix is a simplified *mark* (a logo-small.svg, the way
# kubeNimbus does it) fed in here - not a hand-painted PNG that nothing can
# regenerate.
#
# Needs Inkscape (rasteriser + text-to-path) and, for the social card,
# System.Drawing - so: Windows. Run after any change to design/logo.svg, then
# run scripts/windows/make-app-icons.ps1 to rebuild the shipped icons.
#
#   pwsh scripts/design/make-masters.ps1
param(
    # Override when Inkscape lives somewhere else (or is only on PATH).
    [string]$Inkscape
)
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

$repo      = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$designDir = Join-Path $repo 'design'
$iconDir   = Join-Path $designDir 'masters\icon'
$winDir    = Join-Path $designDir 'masters\window'
$logoDir   = Join-Path $designDir 'masters\logo'
$tmpDir    = Join-Path ([System.IO.Path]::GetTempPath()) ("pgnimbus-masters-" + [guid]::NewGuid().ToString('n'))

foreach ($d in @($iconDir, $winDir, $logoDir, $tmpDir)) { New-Item -ItemType Directory -Force -Path $d | Out-Null }

if (-not $Inkscape) {
    $candidates = @(
        'C:\Program Files\Inkscape\bin\inkscape.com',
        'C:\Program Files (x86)\Inkscape\bin\inkscape.com') +
        @((Get-Command inkscape -ErrorAction SilentlyContinue).Source)
    $Inkscape = $candidates | Where-Object { $_ -and (Test-Path $_) } | Select-Object -First 1
}
if (-not $Inkscape) { throw "Inkscape not found. Install it or pass -Inkscape <path to inkscape.com>." }

function Invoke-Inkscape([string[]]$InkArgs) {
    $out = & $Inkscape @InkArgs 2>&1
    if ($LASTEXITCODE -ne 0) { throw "inkscape $($InkArgs -join ' ') failed:`n$out" }
}

# SVG -> PNG at an exact pixel size. Inkscape honours the <style> block, so the
# .ink/.paper classes render the same way a browser shows them.
function Export-Png([string]$Svg, [string]$Png, [int]$Size) {
    Invoke-Inkscape @($Svg, '--export-type=png', "--export-filename=$Png", '-w', "$Size", '-h', "$Size")
    Write-Host ("wrote {0} ({1}px)" -f ($Png.Substring($repo.Length + 1)), $Size)
}

$light = Join-Path $designDir 'logo.svg'
if (-not (Test-Path $light)) { throw "Missing $light - run scripts/design/af-to-svg.py first." }

# The mark ships in one colourway. The only surface that needs it inverted is
# the unplated Windows title-bar icon below, so the swap lives here, at the
# point of use, rather than as a second SVG in design/ for someone to keep in
# step. (Both classes and the literal fill/stroke attributes carry the value,
# so a plain two-way substitution is the whole job.)
function New-InvertedSvg([string]$SrcSvg, [string]$DstSvg) {
    $svg = Get-Content -Raw $SrcSvg
    $swapped = [regex]::Replace($svg, '#242B36|#F5F7FA',
        { param($m) if ($m.Value -eq '#242B36') { '#F5F7FA' } else { '#242B36' } })
    Set-Content -Path $DstSvg -Value $swapped -Encoding UTF8
}

# ---------------------------------------------------------------- icon tiles
# These end up in app.ico, and app.ico is the one icon Windows hands the
# taskbar, Alt+Tab and the title bar through a single WM_SETICON slot, so it
# cannot be theme-aware. That is why every size keeps the plate: unplated dark
# line art vanishes on a dark taskbar, which is the default. The transparent
# corners outside the plate are fine - what must not be transparent is the
# middle. The theme-aware surfaces are served by the window masters below.
foreach ($size in 16, 24, 32, 48, 256, 1024) {
    Export-Png $light (Join-Path $iconDir "icon-$size.png") $size
}

# ------------------------------------------------------------ window masters
# Transparent line art for the unplated taskbar/Alt+Tab surfaces: the same mark
# with the plate removed, so what is left is the two-tone glyph on transparency.
# Stripping the <circle> from the committed SVG (rather than keeping two more
# hand-maintained files) keeps design/logo*.svg the single source of geometry.
function New-GlyphSvg([string]$SrcSvg, [string]$DstSvg) {
    $svg = Get-Content -Raw $SrcSvg
    $stripped = [regex]::Replace($svg, '\s*<circle[^>]*\br="512"[^>]*/>', '')
    if ($stripped -eq $svg) { throw "No full-bleed plate (r=512) found to strip in $SrcSvg" }
    Set-Content -Path $DstSvg -Value $stripped -Encoding UTF8
}
# This is the one place the palette is inverted, and it earns it: with no plate
# left, what remains on a light surface is a pale field carrying dark line art,
# which sits on a light Start menu as almost nothing. ThemedWindowChrome picks
# between the two by theme at runtime. The name is the theme the icon is used
# *on*, not the colour it is drawn in - so window-light comes off the inverted
# mark.
$inverted = Join-Path $tmpDir 'logo-inverted.svg'
New-InvertedSvg $light $inverted
foreach ($pair in @(
        @{ Src = $inverted; Dst = 'window-light-256.png' },
        @{ Src = $light;    Dst = 'window-dark-256.png' })) {
    $glyph = Join-Path $tmpDir ("glyph-" + $pair.Dst + ".svg")
    New-GlyphSvg $pair.Src $glyph
    Export-Png $glyph (Join-Path $winDir $pair.Dst) 256
}

# -------------------------------------------------------- README header mark
# The full mark at 1024 on transparency, one file: the plate carries the mark's
# own contrast, so it reads on a white README and a dark one without a second
# colourway. icon-1024.png is the same render; this exists because the README
# and the website reference masters/logo/ and would otherwise reach across into
# the icon directory for a file that means something else.
Export-Png $light (Join-Path $logoDir 'logo.png') 1024

# ------------------------------------------------------------------ wordmark
# Horizontal lockup: the mark at 240px beside "pgNimbus" set in Segoe UI Bold.
# The text is baked to paths by Inkscape so the committed SVG renders
# identically on a machine without that font (GitHub's, for one).
$markHeight = 240.0
$markScale  = $markHeight / 1024.0
$gap        = 56.0
$fontSize   = 150.0
$pad        = 24.0

function New-WordmarkSvg([string]$SrcSvg, [string]$TextFill, [string]$DstSvg) {
    $svg = Get-Content -Raw $SrcSvg
    # Body = everything after the </style> close: the mark's own geometry, which
    # carries a literal fill on every path, so dropping class= loses nothing and
    # frees the lockup from needing the <style> block (and from colliding with
    # the text's own fill).
    $body = $svg.Substring($svg.IndexOf('</style>') + '</style>'.Length)
    $body = $body.Substring(0, $body.LastIndexOf('</svg>'))
    $body = [regex]::Replace($body, '\sclass="[^"]*"', '')
    $textX = $markHeight + $gap
    @"
<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="$markHeight" viewBox="0 0 1200 $markHeight">
  <g transform="scale($markScale)">$body</g>
  <text x="$textX" y="$($markHeight / 2)" fill="$TextFill"
        style="font-family:'Segoe UI', Arial, Helvetica, sans-serif;font-weight:700;font-size:${fontSize}px;dominant-baseline:central">pgNimbus</text>
</svg>
"@ | Set-Content -Path $DstSvg -Encoding UTF8
}

# Inkscape's own measurement of the baked document, in px (--query-* is the
# only reliable way to size the lockup: the text's advance width depends on the
# font, so it cannot be hardcoded).
function Get-DocBox([string]$Svg) {
    return @{
        X = [double](& $Inkscape $Svg --query-x)
        Y = [double](& $Inkscape $Svg --query-y)
        W = [double](& $Inkscape $Svg --query-width)
        H = [double](& $Inkscape $Svg --query-height)
    }
}

# Both lockups carry the SAME mark - it needs no colourway of its own. What has
# to change is the type: "pgNimbus" set in ink is unreadable on a dark README.
foreach ($v in @(
        @{ Src = $light; Fill = '#242B36'; Name = 'wordmark-light' },
        @{ Src = $light; Fill = '#F5F7FA'; Name = 'wordmark-dark' })) {
    $raw   = Join-Path $tmpDir "$($v.Name)-raw.svg"
    $baked = Join-Path $logoDir "$($v.Name).svg"
    New-WordmarkSvg $v.Src $v.Fill $raw
    Invoke-Inkscape @($raw, '--export-type=svg', '--export-plain-svg', '--export-text-to-path', "--export-filename=$baked")

    # Tighten the viewBox onto the baked content + uniform padding.
    $box  = Get-DocBox $baked
    $vbX  = [Math]::Round($box.X - $pad, 2)
    $vbY  = [Math]::Round($box.Y - $pad, 2)
    $vbW  = [Math]::Round($box.W + 2 * $pad, 2)
    $vbH  = [Math]::Round($box.H + 2 * $pad, 2)
    $text = Get-Content -Raw $baked
    $text = [regex]::Replace($text, '(<svg\b[^>]*?)\swidth="[^"]*"', '$1', 'Singleline')
    $text = [regex]::Replace($text, '(<svg\b[^>]*?)\sheight="[^"]*"', '$1', 'Singleline')
    $text = [regex]::Replace($text, '(<svg\b[^>]*?)\sviewBox="[^"]*"', '$1', 'Singleline')
    $text = [regex]::Replace($text, '<svg\b', "<svg width=`"$vbW`" height=`"$vbH`" viewBox=`"$vbX $vbY $vbW $vbH`"", 'Singleline')
    Set-Content -Path $baked -Value $text -Encoding UTF8
    Write-Host ("wrote design/masters/logo/$($v.Name).svg ({0} x {1})" -f $vbW, $vbH)

    # PNG fallback at 2x the SVG's own size, for surfaces that will not take SVG.
    Invoke-Inkscape @($baked, '--export-type=png', "--export-filename=$(Join-Path $logoDir "$($v.Name).png")", '-w', "$([int][Math]::Round($vbW * 2))")
    Write-Host "wrote design/masters/logo/$($v.Name).png (2x)"
}

# ------------------------------------------------------------ social preview
# GitHub's repo social card, and the site's og:image: 1280x640, solid
# background (a transparent one renders as white in some clients and black in
# others). It carries the bare mark rather than the wordmark, because link
# unfurlers crop this aggressively and to wildly different aspect ratios - a
# square mark survives that, a 3.7:1 lockup gets its ends eaten. The mark is
# the same mark everything else uses, on a .paper card. Sized off the card's
# HEIGHT (a square sized off the width would overflow
# a 2:1 card) and kept at 62% of it, which leaves a clear margin on the crop
# that square-thumbnail clients apply.
$cardW = 1280; $cardH = 640
$card  = New-Object System.Drawing.Bitmap($cardW, $cardH, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
$g     = [System.Drawing.Graphics]::FromImage($card)
$g.Clear([System.Drawing.Color]::FromArgb(255, 0xF5, 0xF7, 0xFA))   # .paper, matching design/logo.svg
$g.InterpolationMode  = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
$g.PixelOffsetMode    = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality
$g.CompositingQuality = [System.Drawing.Drawing2D.CompositingQuality]::HighQuality
$mark = New-Object System.Drawing.Bitmap((Join-Path $logoDir 'logo.png'))
$targetH2 = [int]($cardH * 0.62)
$targetW2 = [int]($mark.Width * ($targetH2 / $mark.Height))
$g.DrawImage($mark, [int](($cardW - $targetW2) / 2), [int](($cardH - $targetH2) / 2), $targetW2, $targetH2)
$mark.Dispose(); $g.Dispose()
$card.Save((Join-Path $logoDir 'social-preview.png'), [System.Drawing.Imaging.ImageFormat]::Png)
$card.Dispose()
Write-Host "wrote design/masters/logo/social-preview.png (1280x640)"

Remove-Item -Recurse -Force $tmpDir
Write-Host "`nmasters rebuilt. Next: pwsh scripts/windows/make-app-icons.ps1"
